<?php namespace ProcessWire;

class CustomAdminMenus extends WireData implements Module, ConfigurableModule {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Custom Admin Menus',
			'summary' => 'Adds up to three custom dropdowns to the main admin menu.',
			'version' => '0.1.5',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/CustomAdminMenus',
			'icon' => 'caret-down',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.178, PHP>=5.4.0, AdminThemeUikit',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookBefore('ProcessController::execute', $this, 'beforeProcessController');
		$this->addHookAfter('AdminThemeFramework::getPrimaryNavArray', $this, 'afterPrimaryNavArray');
		$this->addHookBefore('ProcessHome::execute', $this, 'beforeProcessHome');
		$this->addHookBefore('ProcessModule::executeEdit', $this, 'addConfigAssets');
	}

	/**
	 * Before ProcessController::execute
	 */
	protected function beforeProcessController(HookEvent $event) {
		// Prevent admin menus from being cached
		$this->wire()->session->removeFor('AdminThemeUikit', 'prnav');
		$this->wire()->session->removeFor('AdminThemeUikit', 'sidenav');
		// Add JS
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config = $this->wire()->config;
		$this->wire()->config->scripts->add($config->urls->$this . "CustomAdminMenus.js?v=$version");
	}

	/**
	 * Get menu children
	 *
	 * @param int $menu_number
	 * @return array
	 */
	protected function ___getMenuChildren($menu_number) {
		$children = [];
		if($menu_number > 0 && $menu_number <= 3) {
			$json = $this->get("menu_{$menu_number}_json");
			$children = $json ? wireDecodeJSON($json) : [];
		}
		foreach($children as $key => $value) {
			$children[$key]['url'] = $this->prepareUrl($children[$key]['url']);
		}
		return $children;
	}

	/**
	 * Prepare link URL
	 *
	 * @param string $url
	 * @return string
	 */
	protected function prepareUrl($url) {
		// Prepend root URL when appropriate
		if($this->prepend_root_url && substr($url, 0, 1) === '/') {
			$url = rtrim($this->wire()->config->urls->root, '/') . $url;
		}
		return $url;
	}

	/**
	 * Prepare menu items array
	 *
	 * @param array $raw_data
	 * @return array
	 */
	protected function prepareMenuItems($raw_data) {
		$items = [];
		foreach($raw_data as $raw_item) {
			if(!isset($raw_item['newtab'])) $raw_item['newtab'] = false;
			$url = $raw_item['newtab'] ? '*' . $raw_item['url'] : $raw_item['url'];
			$children = [];
			if(isset($raw_item['children']) && is_array($raw_item['children'])) $children = $raw_item['children'];
			$items[] = [
				'id' => 0,
				'parent_id' => 0,
				'name' => '',
				'title' => $raw_item['label'],
				'url' => $url,
				'icon' => $raw_item['icon'],
				'children' => $this->prepareMenuItems($children),
				'navJSON' => '',
			];
		}
		return $items;
	}

	/**
	 * After AdminThemeFramework::getPrimaryNavArray
	 */
	protected function afterPrimaryNavArray(HookEvent $event) {
		$items = $event->return;
		for($i = 1; $i <= 3; $i++) {
			$icon = $this->get("menu_{$i}_icon");
			$label = $this->get("menu_{$i}_label");
			if(!$label) continue;
			if($this->get("menu_{$i}_url")) {
				$url = $this->prepareUrl($this->get("menu_{$i}_url"));
			} else {
				$url = $this->wire()->config->urls->admin . "?menu=$i";
			}
			$newtab = $this->get("menu_{$i}_newtab");
			if($newtab) $url = '*' . $url;
			$children = $this->getMenuChildren($i);
			if($children === false) continue;
			$children = $this->prepareMenuItems($children);
			$items[] = [
				'id' => 0,
				'parent_id' => 0,
				'name' => '',
				'title' => $label,
				'url' => $url,
				'icon' => $icon,
				'children' => $children,
				'navJSON' => '',
			];
		}
		$event->return = $items;
	}

	/**
	 * Renders an unordered list
	 *
	 * @param array $children
	 * @return string
	 */
	protected function renderList($children) {
		$out = '<ul>';
		foreach($children as $child) {
			if(!isset($child['newtab'])) $child['newtab'] = false;
			$icon = $child['icon'] ? "<i class='fa fa-fw fa-{$child['icon']}'></i>" : '';
			$url = $child['url'];
			if($child['newtab']) $url = '*' . $url;
			$submenu = '';
			if(!empty($child['children'])) $submenu = $this->renderList($child['children']);
			$out .= "<li><a href='$url'>$icon{$child['label']}</a>$submenu</li>";
		}
		$out .= '</ul>';
		return $out;
	}

	/**
	 * Before ProcessHome::execute
	 *
	 * @param HookEvent $event
	 */
	protected function beforeProcessHome(HookEvent $event) {
		$menu_number = (int) $this->wire()->input->get('menu');
		if(!$menu_number) return;
		$children = $this->getMenuChildren($menu_number);
		if($children) {
			$label = $this->get("menu_{$menu_number}_label");
			if(!$label) return;
			$event->replace = true;
			$this->wire('processBrowserTitle', $label);
			$this->wire('processHeadline', $label);
			$out = <<<EOT
<style>
.cam-menu-list ul { list-style-type:none; padding:0; }
.cam-menu-list ul ul { padding-left:30px; }
.cam-menu-list li { padding-top:8px; }
.cam-menu-list li i { margin-right:5px; }
</style>
EOT;
			$out .= "<div class='cam-menu-list' data-menu='$menu_number'>";
			$out .= $this->renderList($children);
			$out .= '</div>';
			$event->return = $out;
		}
	}

	/**
	 * Add CSS and JS for module config page
	 *
	 * @param HookEvent $event
	 */
	protected function addConfigAssets(HookEvent $event) {
		if($this->wire()->input->get->name !== $this->className) return;
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config = $this->wire()->config;
		$config->styles->add($config->urls->$this . "CustomAdminMenusConfig.css?v=$version");
		$config->scripts->add($config->urls->$this . "CustomAdminMenusConfig.js?v=$version");
	}

	/**
	 * Add markup for a child link row
	 *
	 * @param int $menu_number
	 * @return InputfieldFieldset
	 */
	protected function getMenuFieldset($menu_number) {
		$modules = $this->wire()->modules;
		$labels = [
			'link_icon' => $this->_('Icon'),
			'link_label' => $this->_('Label'),
			'link_url' => $this->_('URL'),
			'link_newtab' => $this->_('New tab'),
			'add_row' => $this->_('Add new'),
		];

		/** @var InputfieldFieldset $f */
		$fs = $modules->get('InputfieldFieldset');
		$fs->label = $this->_('Menu') . " $menu_number";
		$fs->wrapClass('cam-menu');

		/** @var InputfieldText $f */
		$f = $modules->get('InputfieldText');
		$f_name = "menu_{$menu_number}_icon";
		$f->name = $f_name;
		$f->label = $this->_('Icon');
		$f->notes = $this->_('Only shown in sidebar nav.');
		$f->value = $this->$f_name;
		$f->columnWidth = 17;
		$fs->add($f);
		// Menu fieldset is collapsed if the menu has no label
		if(!$f->value) $fs->collapsed = Inputfield::collapsedYes;

		/** @var InputfieldText $f */
		$f = $modules->get('InputfieldText');
		$f_name = "menu_{$menu_number}_label";
		$f->name = $f_name;
		$f->label = $this->_('Label');
		$f->value = $this->$f_name;
		$f->columnWidth = 26;
		$fs->add($f);
		// Menu fieldset is collapsed if the menu has no label
		if(!$f->value) $fs->collapsed = Inputfield::collapsedYes;

		/** @var InputfieldText $f */
		$f = $modules->get('InputfieldText');
		$f_name = "menu_{$menu_number}_url";
		$f->name = $f_name;
		$f->label = $this->_('URL');
		$f->notes = $this->_('If empty the menu will link to a list of child links.');
		$f->value = $this->$f_name;
		$f->columnWidth = 40;
		$fs->add($f);

		/* @var InputfieldCheckbox $f */
		$f = $modules->InputfieldCheckbox;
		$f_name = "menu_{$menu_number}_newtab";
		$f->name = $f_name;
		$f->label = $this->_('Open in new tab');
		$f->checked = $this->$f_name === 1 ? 'checked' : '';
		$f->columnWidth = 17;
		$fs->add($f);

		/** @var InputfieldTextarea $f */
		$f = $modules->get('InputfieldTextarea');
		$f_name = "menu_{$menu_number}_json";
		$f->name = $f_name;
		$f->label = 'Child links JSON';
		$f->wrapClass('cam-menu-json-wrap');
		$f->addClass('cam-menu-json');
		$f->value = $this->$f_name;
		$fs->add($f);

		$json = $this->get("menu_{$menu_number}_json");
		$rows = $json ? wireDecodeJSON($json) : [];
		$class = $rows ? ' has-rows' : '';
		/** @var InputfieldMarkup $f */
		$f = $modules->get('InputfieldMarkup');
		$f->label = $this->_('Child links');
		$f->value = <<<EOT
<div class="cam-row-heads$class">
	<div class="cam-row-sort-wrap"></div>
	<div class="cam-link-icon-wrap"><h3>{$labels['link_icon']}</h3></div>
	<div class="cam-link-label-wrap"><h3>{$labels['link_label']}</h3></div>
	<div class="cam-link-url-wrap"><h3>{$labels['link_url']}</h3></div>
	<div class="cam-link-newtab-wrap"><h3>{$labels['link_newtab']}</h3></div>
	<div class="cam-row-delete-wrap"></div>
</div>
EOT;
		$f->value .= '<div class="cam-row-template">' . $this->childRowMarkup() . '</div>';
		$f->value .= '<div class="cam-child-rows">';
		foreach($rows as $row) {
			$f->value .= $this->childRowMarkup([
				'icon' => $row['icon'],
				'label' => $row['label'],
				'url' => $row['url'],
				'newtab' => $row['newtab'],
			]);
		}
		$f->value .= '</div>';
		$f->value .= "<button type='button' class='cam-add-row'><i class='fa fa-plus-circle'></i> <span class='label'>{$labels['add_row']}</span></button>";
		$fs->add($f);

		return $fs;
	}

	/**
	 * Add markup for a child link row
	 *
	 * @param array $values
	 * @return string
	 */
	protected function childRowMarkup($values = []) {
		if(!$values) $values = [
			'icon' => '',
			'label' => '',
			'url' => '',
			'newtab' => '',
		];
		$checked = $values['newtab'] ? ' checked' : '';
		return <<<EOT
<div class="cam-child-row">
	<div class="cam-row-sort-wrap"><i class="fa fa-fw fa-arrows cam-row-sort"></i></div>
	<div class="cam-link-icon-wrap"><input type="text" class="uk-input cam-link-icon" value="{$values['icon']}"></div>
	<div class="cam-link-label-wrap"><input type="text" class="uk-input cam-link-label" value="{$values['label']}"></div>
	<div class="cam-link-url-wrap"><input type="text" class="uk-input cam-link-url" value="{$values['url']}"></div>
	<div class="cam-link-newtab-wrap"><input type="checkbox" class="uk-checkbox cam-link-newtab"$checked></div>
	<div class="cam-row-delete-wrap"><i class="fa fa-fw fa-trash-o cam-row-delete"></i></div>
</div>
EOT;
	}

	/**
	 * Config inputfields
	 *
	 * @param InputfieldWrapper $inputfields
	 */
	public function getModuleConfigInputfields($inputfields) {
		for($i = 1; $i <= 3; $i++) {
			$inputfields->add($this->getMenuFieldset($i));
		}

		/** @var InputfieldCheckbox $f */
		$f = $this->wire()->modules->get('InputfieldCheckbox');
		$f_name = 'prepend_root_url';
		$f->name = $f_name;
		$f->label = $this->_('Prepend root URL');
		$f->label2 = $this->_('Prepend `$config->urls->root` to URLs that start with a forward slash');
		$f->description = $this->_('This option may be useful if your installation is in a subfolder.');
		$f->checked = $this->$f_name === 1 ? 'checked' : '';
		$f->collapsed = Inputfield::collapsedBlank;
		$inputfields->add($f);
	}

}
